name: Hello Universe
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: marjau/gh-advanced-lkn@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          input_1: "testing 1 2 3"
